Update 01-shellscript

diff --git a/01-shellscript b/01-shellscript
--- a/01-shellscript
+++ b/01-shellscript
@@ -28,7 +28,7 @@ wildfly()
     )
   fi
   echo "wildfly-${VERSION}.Final.zip" | egrep -ow 'wildfly-[0-9]{1,}.(.[0-9]){1,}?.?(Final).zip'
-  [ $? -eq 1 ] && echo "File not found"
+  [ $? -eq 1 ] && echo "File not found" && exit 1
 
   curl -OL --progress-bar "${WILDFLY_BASE_URL}/${VERSION}.Final/wildfly-${VERSION}.Final.zip"
   if [ $DOWNLOADONLY -eq 0 ]
